Enable test suite (#2695)
* use micronaut build kotlin plugins

* remove java version

* add kotlin files

* workaround for https://github.com/google/ksp/issues/2468

* disable test

* Update Micronaut plugin version to 8.0.0-M18

* update platform

* use kotlin mn plugin

* use kotlin mn plugin

* fix kotlin nullability checks

* disable for now

* enable modules

* Issue: Kotlin server interfaces were generated with default parameter values (= null), causing Micronaut runtime NoSuchMethodError on $default methods in controller implementations; fix: stop
     emitting Kotlin default initializers in generated server controller interface methods.

* try fix

* revert mustache change

* fix

* enable MicronautOpenApiTest

* fix mustache

* Fix Kotlin server $default dispatch for optional parameters

* add annotation

* fix test

* trigger build

* Fix OpenAPI config loading in Java generator suite

* Fix Java generator suite to use local OpenAPI annotation processors

* fix KotlinMicronautServerCodegenTest

* revert

* Disable test - core bug

* remove compileArgs

* revert controller-interface.mustache

* update to core 5.0.0

* enable test-suite-spring-kotlin-ksp/src/test/kotlin/io/micronaut/openapi/spring/TestControllerTest.kt

* Address generated resources path review

* Enable Test

* remove empty line

* address sonar failures

* sonar